### ISSUE TITLE
Sprite.resume()

### ISSUE THREAD

**Issue by diogoeichert** [videogamejs/videogamejs#67]
**Is your feature request related to a problem? Please describe.**
I want to be able to make sprites resume their former speed after being paused.

**Describe the solution you'd like**
Calling `Sprite.pause()` and then `Sprite.resume()` afterwards should restore the former speed values.

**Describe alternatives you've considered**
The alternative would be keeping game-specific track of the previous values.

**Additional context**
Can be useful for sprites that should be temporarily paused but able to resume former movement afterwards.
The existing `Sprite.stop()` method should be deprecated and replaced by `Sprite.pause()`.

**Comment by RichardMarks** [comment]
I think that resume should be paired with a pause

It's usually start -> pause -> resume -> stop

**Comment by diogoeichert** [comment]
Sounds better, I've updated the description and the pull request.
